### ISSUE TITLE
图书馆员修改图书状态

### ISSUE THREAD

**Issue by 2455DD** [2455DD/Library-Management-Backend#10]
图书馆员应当可以发布\预定和归还图书项目
(原话: The librarian can also issue, reserve and return book items)

**Comment by cddorz** [comment]
就是图书管理员可以新增书籍，借书，还书是吧

**Comment by 2455DD** [comment]
> 就是图书管理员可以新增书籍，借书，还书是吧

新增书籍不用做,我做了的, 这里的本意是修改图书数量和图书信息, 
借书还书是另外的功能接口

**Comment by cddorz** [comment]
这个接口已经做过了， /updateBookStatus
