### ISSUE TITLE
系统应当可以发送通知

### ISSUE THREAD

**Issue by 2455DD** [2455DD/Library-Management-Backend#12]
系统可以发出图书过期, 预定取消等通知
系统也应当通知会员必须在预定后4小时内借阅本书

**Comment by 2455DD** [comment]
@ZC-A 你这活儿干了多少了啊

**Comment by ZC-A** [comment]
在干，but，我需要知道这个是写好直接让前端调，还是需要我主动发送

**Comment by 2455DD** [comment]
> 在干，but，我需要知道这个是写好直接让前端调，还是需要我主动发送

我能说我没听懂吗……二者间有什么区别

**Comment by ZC-A** [comment]
它这要怎么发通知，发邮件么？还是我只用写到数据库里去查信息返回就行了

**Comment by 2455DD** [comment]
emmmm我问一下Anjag吧

**Comment by 2455DD** [comment]
@ZC-A 所以写的怎么样了
